[build]
  command = "npm install"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/fein-auth"
  to = "/.netlify/functions"
  status = 200

[[redirects]]
  from = "/api/fein-auth/pool"
  to = "/.netlify/functions/fein-auth-pool"
  status = 200
