name = "ff-cloudflare"
main = "src/worker.ts"
compatibility_date = "2024-11-01"

# KV: create via `wrangler kv:namespace create ECR_CACHE`
[[kv_namespaces]]
binding = "ECR_CACHE"
id = "581af8e75125499ca58c3d0ebbf6a0d5"
preview_id = "20b719c98ed7410dbb5d8c770aea3e96"

[vars]
TZ = "America/New_York"
FP_API_KEY = "XmYpBJZPkTg6Ll0Ru6qs23behs6xr972asmNVCy9"

# Put this as a secret in prod:
# wrangler secret put ECR_REFRESH_TOKEN
# For local dev you can also set a placeholder here if you want:
# ECR_REFRESH_TOKEN = "dev-only-value"

# Cron job — runs at 09:10 UTC daily (~05:10 ET during DST)
[triggers]
crons = ["10 9 * * *"]
routes = [
  { pattern = "fortifiedfantasy.com/api/bye-weeks",  zone_name = "fortifiedfantasy.com" },
  { pattern = "fortifiedfantasy.com/api/bye-weeks*", zone_name = "fortifiedfantasy.com" }
]
